export const DATABASE_CONNECTION = 'NEXTAGENT_DATABASE_CONNECTION';

export const REPOSITORIES = {
    agents: 'NEXTAGENT_AGENTS_REPOSITORY',
    users: 'NEXTAGENT_USERS_REPOSITORY',
    owners: 'NEXTAGENT_OWNERS_REPOSITORY',
    suppliers: 'NEXTAGENT_SUPPLIERS_REPOSITORY',
    productCategories: 'NEXTAGENT_PRODUCT_CATEGORIES_REPOSITORY',
    marketplace: 'NEXTAGENT_MARKETPLACE_REPOSITORY',
    products: 'NEXTAGENT_PRODUCTS_REPOSITORY',
    properties: 'NEXTAGENT_PROPERTIES_REPOSITORY',
    propertyMediaImages: 'NEXTAGENT_PROPERTY_MEDIA_IMAGES_REPOSITORY',
    propertyMediaVideos: 'NEXTAGENT_PROPERTY_MEDIA_VIDEOS_REPOSITORY',
    propertyMediaEmbeds: 'NEXTAGENT_PROPERTY_MEDIA_EMBEDS_REPOSITORY',
    propertyMedia360Images: 'NEXTAGENT_PROPERTY_MEDIA_360IMAGES_REPOSITORY',
    propertyMediaFloorPlans: 'NEXTAGENT_PROPERTY_MEDIA_FLOORPLANS_REPOSITORY',
    agentBusinessLocations: 'NEXTAGENT_AGENT_BUSINESS_LOCATIONS_REPOSITORY',
    agentSuppliers: 'NEXTAGENT_AGENT_SUPPLIERS_REPOSITORY',
    supplierProducts: 'NEXTAGENT_SUPPLIER_PRODUCTS_REPOSITORY',
    agentSupplierProduct: 'NEXTAGENT_AGENT_SUPPLIER_PRODUCT_REPOSITORY',
    propertySiteTemplate: 'NEXTAGENT_PROPERTY_SITE_TEMPLATE_REPOSITORY',
    orders: 'NEXTAGENT_ORDERS_REPOSITORY',
};

export const TAGS = {
    login: 'Login',
    agents: 'Agents',
    users: 'Users',
    agentUsers: 'AgentUsers',
    owners: 'Owners',
    ownerUsers: 'OwnerUsers',
    suppliers: 'Suppliers',
    supplierUsers: 'SupplierUsers',
    productCategories: 'ProductCategories',
    marketplace: 'Marketplace',
    products: 'Products',
    properties: 'Properties',
    propertyMediaImages: 'PropertyMediaImages',
    propertyMediaVideos: 'PropertyMediaVideos',
    propertyMediaEmbeds: 'PropertyMediaEmbeds',
    propertyMedia360Images: 'PropertyMedia360Images',
    propertyMediaFloorPlans: 'PropertyMediaFloorPlans',
    agentBusinessLocations: 'AgentBusinessLocations',
    agentSuppliers: 'AgentSuppliers',
    supplierProducts: 'SupplierProducts',
    agentSupplierProduct: 'AgentSupplierProduct',
    propertySiteTemplate: 'PropertySiteTemplate',
    orders: 'Orders',
};

export const ROLES = {
    admin: 'ROLE_ADMIN',
    agent: 'ROLE_AGENT',
    owner: 'ROLE_OWNER',
    supplier: 'ROLE_SUPPLIER',
};
